#!/bin/bash

f=$(realpath "yodatests")
d="${f%/*}"
> "$f"

load()  {
     echo "\"${1##*/}: \" type$ from $1"
}

find $d -maxdepth 1 -type f |
while read t; do
   grep -q "^need check" "$t" &&
   load "$t"  >> "$f"
done

yoda from "$f"
rm "$f"
