#!/bin/bash


#for word in word:dup; do
words=(*)
for word in "${words[@]}"; do
   read -r name _ < <(head -n1 "$word")
   if [[ "$name" == "name:" ]]; then
#      echo "name: $word"
(())
   else
      echo "different: $word"
      echo "$name"
   fi
done
